### ISSUE TITLE
Master is failing

### ISSUE THREAD

**Issue by schneems** [codetriage/CodeTriage#1217]
```
2019-12-23T19:19:10.780770+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/options_cache.rb:12: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
2019-12-23T19:19:10.780950+00:00 app[web.1]: #<Thread:0x00007f230005de88 /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:39 run> terminated with exception (report_on_exception is true):
2019-12-23T19:19:10.781148+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapters/oj.rb:34:in `load': parser io argument must be a String or respond to readpartial() or read(). (ArgumentError)
2019-12-23T19:19:10.781199+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapters/oj.rb:34:in `load'
2019-12-23T19:19:10.781221+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:21:in `load'
2019-12-23T19:19:10.781245+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json.rb:122:in `load'
2019-12-23T19:19:10.781267+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/instruments/puma_instrument.rb:24:in `json_stats'
2019-12-23T19:19:10.781288+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/instruments/puma_instrument.rb:36:in `instrument!'
2019-12-23T19:19:10.781309+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:46:in `block in instrument!'
2019-12-23T19:19:10.781329+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:45:in `each'
2019-12-23T19:19:10.781356+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:45:in `instrument!'
2019-12-23T19:19:10.781377+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:58:in `block (3 levels) in initialize'
2019-12-23T19:19:10.781397+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:57:in `each'
2019-12-23T19:19:10.781417+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:57:in `block (2 levels) in initialize'
2019-12-23T19:19:10.781437+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:46:in `loop'
2019-12-23T19:19:10.781457+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:46:in `block in initialize'
2019-12-23T19:19:10.782032+00:00 app[web.1]: [92] ! Detected parent died, dying
2019-12-23T19:19:10.782176+00:00 app[web.1]: [88] ! Detected parent died, dying
2019-12-23T19:19:10.789908+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapters/oj.rb:34:in `load': parser io argument must be a String or respond to readpartial() or read(). (ArgumentError)
2019-12-23T19:19:10.789955+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapters/oj.rb:34:in `load'
2019-12-23T19:19:10.789980+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:21:in `load'
2019-12-23T19:19:10.790016+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/multi_json-1.13.1/lib/multi_json.rb:122:in `load'
2019-12-23T19:19:10.790041+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/instruments/puma_instrument.rb:24:in `json_stats'
2019-12-23T19:19:10.790068+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/instruments/puma_instrument.rb:36:in `instrument!'
2019-12-23T19:19:10.790094+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:46:in `block in instrument!'
2019-12-23T19:19:10.790122+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:45:in `each'
2019-12-23T19:19:10.790149+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/panel.rb:45:in `instrument!'
2019-12-23T19:19:10.790173+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:58:in `block (3 levels) in initialize'
2019-12-23T19:19:10.790197+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:57:in `each'
2019-12-23T19:19:10.790223+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:57:in `block (2 levels) in initialize'
2019-12-23T19:19:10.790247+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:46:in `loop'
2019-12-23T19:19:10.790274+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/barnes-0.0.7/lib/barnes/periodic.rb:46:in `block in initialize'
```

Had to rollback to 

```
v1386  Deploy 4c344a7d                    <email>   2019/12/18 17:04:08 -0600
```

**Comment by hbontempo-br** [comment]
Can we close please?
