### ISSUE TITLE
Not able to select a language in the Filter List by Language LOV

### ISSUE THREAD

**Issue by shivayanbora123** [codetriage/codetriage#544]
I am not able to select a language in the Filter List by Language LOV, but instead, I am seeing the below help text after clicking the LOV:

**Pick your favorite repos to receive a different open issue in your inbox every day. Fix the issue and everybody wins. 19,950 developers are working on 2632 open source repos using CodeTriage.**

![capture1](https://cloud.githubusercontent.com/assets/23340497/26485009/c6024154-4212-11e7-980a-961909fc7d0f.PNG)
 
Also in the Developer Tools, I am able to see the below-mentioned exception although I'm not sure if this is related to this:

chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://www.codetriage.com" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)

**Comment by nateberkopec** [comment]
Seeing the same behavior. The console error you're getting is just one of your chrome extensions, though.

**Comment by nateberkopec** [comment]
I think it's this: https://github.com/codetriage/codetriage/commit/f56406db16ed935178bc2ddb1f59be3349672535

@schneems added two caches to the same page, but didnt specify a key. Silly @schneems.

**Comment by shivayanbora123** [comment]
Ah ok.... I kinda thought that might've been the issue.... Now I feel silly that the message was related to one of my extensions and not at all related to the issue.... A total newbie here.... I gotta look at the messages more thoroughly... Thanks for this though... :) @nateberkopec

**Comment by nateberkopec** [comment]
No prob! FWIW you can use Incognito Mode in Chrome and it'll disable all extensions.
