### ISSUE TITLE
Intermittent user mailer test

### ISSUE THREAD

**Issue by jhsu802701** [codetriage/codetriage#901]
When running the test suite, I sometimes get the following error:
```
Error:                                                                          
UserMailerTest#test_poke_inactive_works:                                        
ActionView::Template::Error: undefined method `full_name' for nil:NilClass
    app/views/user_mailer/poke_inactive.html.erb:13:in `_app_views_user_mailer_p
oke_inactive_html_erb___374816158_41059430'           
    app/mailers/user_mailer.rb:79:in `poke_inactive'
    test/functional/user_mailer_test.rb:19:in `block (2 levels) in <class:UserMa
ilerTest>'                                                                      
    test/functional/user_mailer_test.rb:18:in `block in <class:UserMailerTest>'
```

**Comment by prathamesh-sonpatki** [comment]
Closed by #909
